title: Prof. Makissuel
description: Blog de Estudos

url: https://makissuelms.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Início
      url: /index.html
    - title: Sobre
      url: /about
    - title: Contato
      url: /contact

social:
    github: makissuelms
    twitter: makissuelms
    facebook: makissuelms
    email: makissuelms@pronton.me
    linkedin: 
    youtube: 
    tumblr: 

google_analytics: ""

disqus:
    shortname: makissuelms
